spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  redis:
    host: localhost
    port: 6379
  datasource:
    username: gobook
    password: gobook
    url: jdbc:mysql://localhost:3306/gobook?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.hibernate:
      SQL: error
      type.descriptor.sql.BasicBinder: trace
app:
  host: http://localhost:8080
server:
  tomcat:
    max-http-form-post-size: 5MB
<<<<<<< HEAD
jwt:
  secret: qlxmrydbrtpsxjzkrxpdlfvmfhwprxmfhrmdlsrorkxekwjdakf
data.rest:
  base-path: /api
  detection-strategy: annotated
# mvc:
# hiddenmethod:
# filter:
# enabled: true
=======
    
jwt:
  secret: qlxmrydbrtpsxjzkrxpdlfvmfhwprxmfhrmdlsrorkxekwjdakf
    
 # mvc:
 #   hiddenmethod:
  #    filter:
  #      enabled: true
>>>>>>> refs/remotes/origin/master
